Npm token loader begin with home page
Mohammad1Fawaz/TaskManagementSystem pull request #2
Opened 2024-02-04 19:19 UTC by Yasser-AliAhmad

2024-02-05 16:31 UTC, Mohammad1Fawaz requested changes

2024-02-05 16:31 UTC, Mohammad1Fawaz commented on TaskManagementSystem.Server/Services/UserService.cs
> +                return new UserResultWithToken(false, "Invalid Login, wrong email or password", null);
For UserResultWithToken :
        public UserResultWithToken(bool success, string message, string token = null)
        {
            this.success = success;
            this.message = message;
            this.token = token;
        }
        then no need to send token as null when it's no needed .
it will be : return new UserResultWithToken(false, "Invalid Login, wrong email or password");

2024-02-05 16:31 UTC, Mohammad1Fawaz commented on TaskManagementSystem.Server/ViewModels/UserViewModels/UserResultWithToken.cs
> +        public UserResultWithToken(bool success, string message, string token)
see the comment above

2024-02-05 16:31 UTC, Mohammad1Fawaz commented on TaskManagementSystem.Server/ViewModels/UserViewModels/UserTokenValidationResult.cs
> +    public class UserTokenValidationResult
camel case for variables

2024-02-05 16:31 UTC, Mohammad1Fawaz commented on taskmanagementsystem.client/src/App.jsx
>          populateWeatherData();
2 useEffect ??????
 
remove the function populateWeatherData

2024-02-05 16:31 UTC, Mohammad1Fawaz commented on taskmanagementsystem.client/src/App.jsx
> +            console.log("token: ", token);
what we will gain from the token if we logged it in the console !

2024-02-05 16:31 UTC, Mohammad1Fawaz commented on taskmanagementsystem.client/src/Components/UserForms/UserLoginForm.jsx
> +            const result = await loginUser(formData, setIsLoading);
why you are sending setIsLoading as parameter and you are getting the result here.
you can just put setIsLoading(false) after if else statement.

2024-02-05 16:31 UTC, Mohammad1Fawaz commented on taskmanagementsystem.client/src/Components/UserForms/UserRegistrationForm.jsx
> +            const result = await registerUser(formData, setIsLoading);
Same

2024-02-05 16:31 UTC, Mohammad1Fawaz commented on taskmanagementsystem.client/src/Components/ui/PrimaryButton.jsx
> +    return <button type={type} className="btn btn-primary w-100" disabled={isLoading}>
if we want to use this button in all the solution , we can't use it with width 100%
(w-100)

2024-02-05 16:31 UTC, Mohammad1Fawaz commented on taskmanagementsystem.client/src/Services/UserFormsService/AuthService.jsx
> +        setIsLoading(false);
remove setIsLoading from here

2024-02-05 16:31 UTC, Mohammad1Fawaz commented on taskmanagementsystem.client/src/Services/UserFormsService/AuthService.jsx
> +export const loginUser = async (userData, setIsLoading) => {
Same

2024-02-05 16:31 UTC, Mohammad1Fawaz commented on taskmanagementsystem.client/src/Services/UserFormsService/AuthService.jsx
> +export const VerifiyUser = async (token, setIsLoading) => {
Same , and make (VerifyUser) camel case

2024-02-05 16:31 UTC, Mohammad1Fawaz commented on taskmanagementsystem.client/src/utils/user.js
> +export function saveToken(token) {
why this function created here and not in AuthService if it's related to the user authentication?

2024-02-05 18:26 UTC, Yasser-AliAhmad commented on taskmanagementsystem.client/src/utils/user.js
> +export function saveToken(token) {
we may use it with other APIs

2024-02-06 12:45 UTC, Mohammad1Fawaz requested changes

2024-02-06 12:45 UTC, Mohammad1Fawaz commented on taskmanagementsystem.client/src/App.jsx
>                      <Route path="/h" element={<Home />} />
remove this : <Route path="/h" element={<Home />} />

2024-02-06 12:45 UTC, Mohammad1Fawaz commented on taskmanagementsystem.client/src/Components/CommonComponents/MediumLogo.jsx
>          <div className="d-flex justify-content-center MediumLogo mb-3">
To avoid using multiple logos component in future as you suggest  .I think it's better to send the size of the logo image directly without static class (MediumLogo) ,so rename the component MediumLogo to be Logo with its size.

2024-02-06 12:45 UTC, Mohammad1Fawaz commented on taskmanagementsystem.client/src/Components/ui/PrimaryButton.jsx
> +    return <button type={type} className="btn btn-primary" style={{width: width || "100%"}} disabled={isLoading}>
using inline styles will leads to caching , performance and conflicts  issues later  . so it's better to send the width as class .

2024-02-06 12:45 UTC, Mohammad1Fawaz commented on taskmanagementsystem.client/src/index.css
> +.nav-bg {
if this classes is only for nav bar , and it will not be used in all solution . why you put them here ?

2024-02-06 12:58 UTC, Mohammad1Fawaz requested changes

2024-02-06 12:58 UTC, Mohammad1Fawaz commented on taskmanagementsystem.client/src/Components/UserForms/VerificationPage.jsx
> +import { verifyUser, errorNotify, successNotify } from '../../Services/UserFormsService/AuthService';
To avoid calling all notification components each time, it is better to create a global function that can be used throughout the entire solution. This function should accept parameters specifying the type of notification and the corresponding message.

2024-02-08 19:11 UTC, merged